//
// Created by muham on 31.03.2026.
//

#ifndef CORTEXMIND_RUNTIME_FLAGS_DEFAULTS_HPP
#define CORTEXMIND_RUNTIME_FLAGS_DEFAULTS_HPP

#define CXM_EXIT 0
#define CXM_ERR_EXIT 1

#endif //CORTEXMIND_RUNTIME_FLAGS_DEFAULTS_HPP