//
// Created by muham on 8.04.2026.
//

#ifndef CORTEXMIND_RUNTIME_MACROS_HPP
#define CORTEXMIND_RUNTIME_MACROS_HPP

#define CXM_SAFE_EXIT 0
#define CXM_ERR_EXIT  1

#define CXM_HOST_DEVICE 0x2887LL
#define CXM_CUDA_DEVICE 0x2888LL

#define CXM_VERSION_MAJOR 3
#define CXM_VERSION_MINOR 1
#define CXM_VERSION_PATCH 0

#endif //CORTEXMIND_RUNTIME_MACROS_HPP