//
// Created by muham on 8.05.2026.
//

#ifndef CORTEXMIND_RUNTIME_MACROS_HPP
#define CORTEXMIND_RUNTIME_MACROS_HPP

#define CXM_EXIT 0
#define CXM_ERR_EXIT 1

#define CXM_HOST_DEVICE 0x2887LL
#define CXM_CUDA_DEVICE 0x2888LL

#define CXM_MAX_DIMS 4

#define CXM_DEFAULT_POOL_SIZE ((128) * (1024) * (1024))

#endif //CORTEXMIND_RUNTIME_MACROS_HPP